---
apiVersion: v1
kind: Secret
metadata:
  namespace: rust-hello
  name: rust-hello-db-secrets
type: Opaque
stringData:
  postgres-password: $POSTGRES_PASSWORD
  replication-password: $POSTGRES_REPLICATION_PASSWORD
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  namespace: rust-hello
  name: rust-hello-db
spec:
   replicas: 2
   image: postgres:14
   database:
      size: 4Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: rust-hello-db-secrets
              key: postgres-password
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: rust-hello-db-secrets
              key: replication-password
